### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by hpx7** [geckosio/phaser-on-nodejs#16]
I get the following error when I try to run `npm i @geckos.io/phaser-on-nodejs`:
```
npm ERR! Package pangocairo was not found in the pkg-config search path.
npm ERR! Perhaps you should add the directory containing `pangocairo.pc'
npm ERR! to the PKG_CONFIG_PATH environment variable
npm ERR! No package 'pangocairo' found
npm ERR! gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

...

npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "~/.nvm/versions/node/v17.3.0/bin/node" 
npm ERR! gyp ERR! node -v v17.3.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
```

**Comment by hpx7** [comment]
It appears to be an issue with installing `canvas`. Might have something to do with the fact that I'm using an M1 mac

**Comment by yandeu** [comment]
> It appears to be an issue with installing `canvas`.

Yes it looks like that:
https://github.com/Automattic/node-canvas#compiling

Maybe try this package instead:
https://github.com/yandeu/arcade-physics

**Comment by hpx7** [comment]
Cool I was able to get arcade-physics working (in case you're curious: https://github.com/hpx7/hathora-phaser-demo)

**Comment by yandeu** [comment]
Nice! And `arcade-physics` is also much faster than `phaser-on-nodejs`.
