### ISSUE TITLE
Phaser not working in headless mode with "npm geckos.io/phaser-on-node"

### ISSUE THREAD

**Issue by mreifenberger** [geckosio/phaser-on-nodejs#3]
I tried running phaser on my server in headless mode, and wanted to use your geckos.io/phaser-on-node dependency. After requiring it in my config I still get the error 
if (window.hasOwnProperty('webkitAudioContext') &&
  ^
ReferenceError: window is not defined

repo to replicate: https://gitlab.com/mreifenberger/phaser3-typescript-multiplayer-template

Thank you for any help,
Mika

**Comment by yandeu** [comment]
I [fixed it here](https://github.com/yandeu/temp). There where a LOT of issues. But nothing wrong with phaser-on-nodejs :)

- Clone the repo
- run `npm i` to install dependencies
- run `npm run blabla` to start development

Hope this helps :)

**Comment by mreifenberger** [comment]
Hi Yannic,

thank you VERY much for looking into that. (Sorry for wasting your time tho now that geckosio runs perfectly fine unlike i said).

It helped me tremendously, thank you :)
